name: faux_admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.2
  cloudinary: ^1.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  image_picker_for_web: ^2.1.10
  permission_handler: ^10.1.0
  shared_preferences: ^2.0.15
  toast: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
